version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ansi-escapes
    versions:
    - 4.3.1
    - 4.3.2
  - dependency-name: ora
    versions:
    - 5.3.0
  - dependency-name: chalk
    versions:
    - 4.1.0
